export const movies = [
    {
        "id": 76,
        "nameRU": " Возможности безграничны",
        "nameEN": "The Possibilities Are Endless",
        "director": "Джеймс Холл, Эдвард Лавлэйс",
        "country": "Великобритания, США",
        "year": "2014",
        "duration": 83,
        "description": "Десять лет назад его хватил удар — он был в коме шесть месяцев и мог выговаривать только слова «да», «нет», «Грейс Максвелл» (имя его жены и менеджера) и «возможности безграничны». Он — Эдвин Коллинс: фронтмен прославленной шотландской постпанк-группы Orange Juice. Несмотря ни на что, он записал несколько сольных альбомов. «Possibilities Are Endless» — это экспериментальный, невероятно красиво снятый документальный фильм: с абстрактными картинами родного для героя Хелмсдейла, трогательными сценами помощи Грейс Коллинсу, который все-таки смог еще появиться на сцене. В равной степени — попытка понять чувства пережившего инсульт, история одной великой любви и высказывание о безграничной силе музыки.",
        "trailerLink": "https://www.youtube.com/watch?v=2pCKC9MioDA",
        "created_at": "2020-12-03T16:59:17.595Z",
        "updated_at": "2020-12-03T16:59:17.595Z",
        "image": {
            "id": 77,
            "name": "maxresdefault (2)",
            "alternativeText": "",
            "caption": "",
            "width": 1280,
            "height": 720,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_maxresdefault_2_3072271808",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 11.14,
                    "path": null,
                    "url": "/uploads/thumbnail_maxresdefault_2_3072271808.jpeg"
                },
                "large": {
                    "hash": "large_maxresdefault_2_3072271808",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 1000,
                    "height": 563,
                    "size": 207.98,
                    "path": null,
                    "url": "/uploads/large_maxresdefault_2_3072271808.jpeg"
                },
                "medium": {
                    "hash": "medium_maxresdefault_2_3072271808",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 422,
                    "size": 119.53,
                    "path": null,
                    "url": "/uploads/medium_maxresdefault_2_3072271808.jpeg"
                },
                "small": {
                    "hash": "small_maxresdefault_2_3072271808",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 281,
                    "size": 50.39,
                    "path": null,
                    "url": "/uploads/small_maxresdefault_2_3072271808.jpeg"
                }
            },
            "hash": "maxresdefault_2_3072271808",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 327.2,
            "url": "/uploads/maxresdefault_2_3072271808.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T16:57:41.958Z",
            "updated_at": "2020-12-03T16:57:41.958Z"
        }
    },
    {
        "id": 77,
        "nameRU": "Ламберт и Стэмп",
        "nameEN": "Lambert & Stamp",
        "director": "Джеймс Д. Купер",
        "country": "США",
        "year": "2014",
        "duration": 117,
        "description": "Свингующий Лондон конца 60-х — начала 70-х. Темные очки, галстуки, оллнайтеры и прочие атрибуты самых первых модов. Группа, написавшая песню «My Generation» и рок-оперу «Tommy». Все это «Lambert & Stamp» — не столько портрет менеджеров группы The Who, вообще-то, сначала мечтавших снять о ней документальный фильм, сколько рассказ о начале самой прекрасной эпохи для гитарной музыки. Как в одном музыкальном коллективе работники офиса и завода уживались со студентом арт-школы и гениальным барабанщиком, чинившим радио? Почему два совершенно разных человека — гей-интеллектуал и брат актера Теренса Стэмпа — решили их продюсировать, хотя считали уродливыми? Насколько огромную роль все они сыграли для своего времени — и что со всеми с ними стало после успеха? Все это заинтересовало отлично дебютировавшего режиссера Джеймса Д.Купера.",
        "trailerLink": "https://www.youtube.com/watch?v=YMaRbIBUvps",
        "created_at": "2020-12-03T17:04:21.375Z",
        "updated_at": "2020-12-03T17:04:21.375Z",
        "image": {
            "id": 78,
            "name": "images",
            "alternativeText": "",
            "caption": "",
            "width": 300,
            "height": 168,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_images_f324307a7f",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 137,
                    "size": 8.17,
                    "path": null,
                    "url": "/uploads/thumbnail_images_f324307a7f.jpeg"
                }
            },
            "hash": "images_f324307a7f",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 10.05,
            "url": "/uploads/images_f324307a7f.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T17:01:26.006Z",
            "updated_at": "2020-12-03T17:01:26.006Z"
        }
    },
    {
        "id": 78,
        "nameRU": "Ли Скретч Перри: Виденье рая",
        "nameEN": "Lee Scratch Perry’s Vision of Paradise",
        "director": "Фолькер Шанер",
        "country": "Германия, Великобритания, Швейцария, Ямайка, Эфиопия",
        "year": "2015",
        "duration": 100,
        "description": "Перед тем как стать человеком, он был рыбой. Сейчас Ли «Скретч» Перри называет себя не иначе как Ноем. Его религия — его сердце; его законы просты — ганджа должна быть свободной, а бога нужно развлекать. Он продюсировал Боба Марли и писал альбом с The Orb, работал с Китом Ричардсом, Beastie Boys и Дэвидом Линчем, научил многих музыкантов пользоваться студией как инструментом и выпустил не один грандиозный даб-альбом. Он разговаривает с коровой и каждое утро вслух приветствует свой компьютер, кружится с раскинутыми руками вокруг Букингемского дворца и напоминает, что все тени одного цвета. «Visions of Paradise» — это документальная сказка по мотивам 13 лет, проведенных немецким режиссером Фолькером Шанером в компании Ли Перри, от Ямайки и Эфиопии до Швейцарии и Лондона. Герой в ней предстает то ли поехавшим дедом, рассуждающим о космических путешествиях, то ли настоящим магом. То есть, вообще говоря, как тем, так и другим.",
        "trailerLink": "https://www.youtube.com/watch?v=9mvjnZAgUNA",
        "created_at": "2020-12-03T17:09:04.230Z",
        "updated_at": "2020-12-03T17:09:04.230Z",
        "image": {
            "id": 79,
            "name": "unnamed",
            "alternativeText": "",
            "caption": "",
            "width": 512,
            "height": 362,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_unnamed_4f99c0fa1e",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 221,
                    "height": 156,
                    "size": 12.75,
                    "path": null,
                    "url": "/uploads/thumbnail_unnamed_4f99c0fa1e.jpeg"
                },
                "small": {
                    "hash": "small_unnamed_4f99c0fa1e",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 354,
                    "size": 56.29,
                    "path": null,
                    "url": "/uploads/small_unnamed_4f99c0fa1e.jpeg"
                }
            },
            "hash": "unnamed_4f99c0fa1e",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 60.22,
            "url": "/uploads/unnamed_4f99c0fa1e.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T17:04:50.419Z",
            "updated_at": "2020-12-03T17:04:50.419Z"
        }
    },
    {
        "id": 79,
        "nameRU": "Любимый небесами",
        "nameEN": "Heaven Adores You",
        "director": "Николас Дилан Росси",
        "country": "США",
        "year": "2014",
        "duration": 104,
        "description": "«Я не то чтобы хотел стать знаменитым», — неуверенным, немного ноющим голосом говорит музыкант, для которого номинация его песни на «Оскар» стала нелепым, странным и пугающим событием. В 2003 году он, согласно одной из версий, покончил с собой, воткнув нож себе в грудь. Вразрез с угрюмым началом «Heaven Adores You» — это удивительно духоподъемный, бережно, с обожанием и преданностью сконструированный фильм не об ужасной истории сгорания, не о зависимостях и депрессии, но о прекрасном человеке и музыканте, который жив до сих пор, пусть так только кажется после просмотра. Интервью друзей и причастных, ранее не слышанная музыка и другие раскопки вроде фотографий со школьными друзьями, картины гордов, включая Портленд, где он был знаменит, пока всему миру было наплевать, и Лос-Анджелес, где на бульваре Сансет есть стена в его честь.",
        "trailerLink": "https://www.youtube.com/watch?v=qYy_OBMdcQo",
        "created_at": "2020-12-03T17:10:52.837Z",
        "updated_at": "2020-12-03T17:10:52.837Z",
        "image": {
            "id": 80,
            "name": "загруженное",
            "alternativeText": "",
            "caption": "",
            "width": 275,
            "height": 183,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_a32e347316",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 234,
                    "height": 156,
                    "size": 9.22,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_a32e347316.jpeg"
                }
            },
            "hash": "zagruzhennoe_a32e347316",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 9.76,
            "url": "/uploads/zagruzhennoe_a32e347316.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T17:09:56.363Z",
            "updated_at": "2020-12-03T17:09:56.363Z"
        }
    },
    {
        "id": 80,
        "nameRU": "От станции к станции",
        "nameEN": "Station to Station",
        "director": "Даг Эйткен",
        "country": "США",
        "year": "2015",
        "duration": 71,
        "description": "Бродячий оркестр из музыкантов, художников, архитекторов, фотографов и танцоров едет на поезде из Нью-Йорка в Окленд.\n\n24 дня, 10 остановок, два океана- один железнодорожный путь калифорниец Дуг Айткен превратил в 61 мини-фильм. В каждом из них заснят как поезд, очень красиво светящийся светодиодами, так и непосредственный момент создания того или иного произведения, будь то концерт Бека с госпельным хором, рисующая машина Олафура Элиассона или негромко поющий Эриэл Пинк в колготках. Все они кратко рассказывают, что думают о путешествиях, жизни, индустрии и вообще своей работе, попутно описывая собственные творческие методы.\n\nЗритель выступает то как собеседник этих грандиозных личностей, то как пассажир, который смотрит на Америку из окна, то как сторонний наблюдатель этой конструкции, несущейся куда-то прямо в вечность.",
        "trailerLink": "https://www.youtube.com/watch?v=FNWN0N0b1qc",
        "created_at": "2020-12-03T17:12:50.705Z",
        "updated_at": "2020-12-03T17:12:50.705Z",
        "image": {
            "id": 81,
            "name": "maxresdefault",
            "alternativeText": "",
            "caption": "",
            "width": 1280,
            "height": 720,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_maxresdefault_164e1c974c",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 7.36,
                    "path": null,
                    "url": "/uploads/thumbnail_maxresdefault_164e1c974c.jpeg"
                },
                "large": {
                    "hash": "large_maxresdefault_164e1c974c",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 1000,
                    "height": 563,
                    "size": 63.81,
                    "path": null,
                    "url": "/uploads/large_maxresdefault_164e1c974c.jpeg"
                },
                "medium": {
                    "hash": "medium_maxresdefault_164e1c974c",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 422,
                    "size": 41.32,
                    "path": null,
                    "url": "/uploads/medium_maxresdefault_164e1c974c.jpeg"
                },
                "small": {
                    "hash": "small_maxresdefault_164e1c974c",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 281,
                    "size": 22.08,
                    "path": null,
                    "url": "/uploads/small_maxresdefault_164e1c974c.jpeg"
                }
            },
            "hash": "maxresdefault_164e1c974c",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 87.68,
            "url": "/uploads/maxresdefault_164e1c974c.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T17:12:02.905Z",
            "updated_at": "2020-12-03T17:12:02.905Z"
        }
    },
    {
        "id": 81,
        "nameRU": "Берроуз",
        "nameEN": "Burroughs: The Movie",
        "director": "Ховард Брукнер",
        "country": "США",
        "year": "1983",
        "duration": 86,
        "description": "Первый и единственный длинный документальный фильм о великом контркультурном писателе, который с большим удовольствием становится под прицел видеокамеры. Режиссер Говард Брукнер начал работать над «Burroughs» в 1978-м как над выпускной работой из Нью-Йоркского университета. Закончил в 1983-м, проведя много времени и с самим Берроузом, и с его друзьями и последователями. В кадре появляются Аллен Гинзберг и Патти Смит, оператор — Том Дичилло, звук вообще записан товарищем Брукнера по имени Джим Джармуш. Брукнер умер в 1989-м — к столетию со дня рождения Берроуза, в 2014-м, всего несколько раз показанный фильм был доделан и перевыпущен племянником режиссера. От США до Северной Африки, от чтения отрывков из «Голого завтрака» до воспоминаний о мололодости, от бесценных монологов до живого и порой очень смешного общения героя с другими людьми — обо всем этом с бесконечной демонической привлекательностью.",
        "trailerLink": "https://www.youtube.com/watch?v=5m_1N_phcjo",
        "created_at": "2020-12-03T18:02:11.621Z",
        "updated_at": "2020-12-03T18:02:11.621Z",
        "image": {
            "id": 82,
            "name": "b80915f7-d774-4536-9e79-450578a40ad4-9131a274",
            "alternativeText": "",
            "caption": "",
            "width": 640,
            "height": 360,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 5.38,
                    "path": null,
                    "url": "/uploads/thumbnail_b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520.jpeg"
                },
                "small": {
                    "hash": "small_b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 281,
                    "size": 17.46,
                    "path": null,
                    "url": "/uploads/small_b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520.jpeg"
                }
            },
            "hash": "b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 25.39,
            "url": "/uploads/b80915f7_d774_4536_9e79_450578a40ad4_9131a274_04cd1fb520.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T17:58:43.203Z",
            "updated_at": "2020-12-03T17:58:43.203Z"
        }
    },
    {
        "id": 82,
        "nameRU": "Бэнкси уделывает Нью-Йорк",
        "nameEN": "Banksy Does New York",
        "director": " Крис Мукарбел",
        "country": "США",
        "year": "2014",
        "duration": 79,
        "description": "В октябре 2013-го Бэнкси решил устроить, пожалуй, самую масштабную свою выставку — и за месяц прошелся по Нью-Йорку, точно ураган. Каждый день он — разумеется, анонимно — выходил на улицу, чтобы превратить очередной клочок стены или закоулок квартала, до того не видавшего паблик-арта, в масштабную арт-инсталляцию, тем самым заставляя охотиться за собой одновременно толпы местных жителей и полицию. Все это дало эффект, сам по себе являющийся лучшим комментарием к современному искусству: люди не только снимали все происходящее на мобильный телефон, выкладывали в инстаграм и проставляли хэштеги, тем самым становясь частью экспозиции, — но и похищали работы, брали деньги с желающих их сфотографировать и даже вырывали с корнем, чтобы потом продать в какую-нибудь престижную галерею современного искусства.",
        "trailerLink": "https://www.youtube.com/watch?v=BMnoLW1RZ8I",
        "created_at": "2020-12-03T18:04:53.958Z",
        "updated_at": "2020-12-03T18:04:53.958Z",
        "image": {
            "id": 83,
            "name": "12032-770x433",
            "alternativeText": "",
            "caption": "",
            "width": 770,
            "height": 433,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_12032_770x433_74026cdeb6",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 7.85,
                    "path": null,
                    "url": "/uploads/thumbnail_12032_770x433_74026cdeb6.jpeg"
                },
                "medium": {
                    "hash": "medium_12032_770x433_74026cdeb6",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 422,
                    "size": 61.29,
                    "path": null,
                    "url": "/uploads/medium_12032_770x433_74026cdeb6.jpeg"
                },
                "small": {
                    "hash": "small_12032_770x433_74026cdeb6",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 281,
                    "size": 29.49,
                    "path": null,
                    "url": "/uploads/small_12032_770x433_74026cdeb6.jpeg"
                }
            },
            "hash": "12032_770x433_74026cdeb6",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 66.03,
            "url": "/uploads/12032_770x433_74026cdeb6.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:04:02.124Z",
            "updated_at": "2020-12-03T18:04:02.124Z"
        }
    },
    {
        "id": 83,
        "nameRU": "Айрис",
        "nameEN": "Iris",
        "director": null,
        "country": "США",
        "year": "2014",
        "duration": 83,
        "description": "В молодости один владелец магазина заявил ей, что она не очень красивая, но это не так уж важно, поскольку у нее «есть стиль — и это гораздо лучше». За все следующие годы Айрис Апфель, которая не покладая рук работает в моде с 50-х и которой на момент показа будет 93 года, ни разу не опровергла это утверждение о стиле. Круглые очки и гигантские украшения, бесконечные гардеробы, обложка Dazed и Дрис ван Нотен с Канье Уэстом в поклонниках — все это Айрис. А еще у нее есть столетний муж Карл, с которым Айрис вместе с 1948-го, так что ее слова «Гораздо важнее быть счастливым, чем хорошо одетым», — это ничуть не лукавство: вот уж кто знает, о чем говорит. Не менее важный герой фильма — его режиссер Альберт Мейзелс, автор «Серых садов» и «Gimme Shelter» о The Rolling Stones, скончавшийся в этом году в 83 года. «Iris» стал одним из его последних фильмов — он следовал за героиней по всему Манхэттену, добавив интервью ее почитателей и кадры с «Никона» и 16-миллиметровой кинопленки из семейного архива.",
        "trailerLink": "https://www.youtube.com/watch?v=cc5wu-TIQao",
        "created_at": "2020-12-03T18:06:46.077Z",
        "updated_at": "2020-12-03T18:06:46.077Z",
        "image": {
            "id": 84,
            "name": "загруженное (1)",
            "alternativeText": "",
            "caption": "",
            "width": 310,
            "height": 163,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_1_70b0c1a682",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 129,
                    "size": 14.38,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_1_70b0c1a682.jpeg"
                }
            },
            "hash": "zagruzhennoe_1_70b0c1a682",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 20.55,
            "url": "/uploads/zagruzhennoe_1_70b0c1a682.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:06:15.128Z",
            "updated_at": "2020-12-03T18:06:15.128Z"
        }
    },
    {
        "id": 84,
        "nameRU": "Boiler Room – Stay in Russia",
        "nameEN": "",
        "director": "Александра Худоконя, Лейлы Машариповой",
        "country": "Россия",
        "year": "2015",
        "duration": 14,
        "description": "Документальный фильм про российских бит-мейкеров, ставших участниками Boiler Room. В фильме также принимают участие DJ Premier, Samiyam и Nx Worries.",
        "trailerLink": "https://vimeo.com/129794961",
        "created_at": "2020-12-03T18:08:51.563Z",
        "updated_at": "2020-12-03T18:08:51.563Z",
        "image": {
            "id": 85,
            "name": "maxresdefault (1)",
            "alternativeText": "",
            "caption": "",
            "width": 1280,
            "height": 720,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_maxresdefault_1_5bef2a2c64",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 6.98,
                    "path": null,
                    "url": "/uploads/thumbnail_maxresdefault_1_5bef2a2c64.jpeg"
                },
                "large": {
                    "hash": "large_maxresdefault_1_5bef2a2c64",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 1000,
                    "height": 563,
                    "size": 61.45,
                    "path": null,
                    "url": "/uploads/large_maxresdefault_1_5bef2a2c64.jpeg"
                },
                "medium": {
                    "hash": "medium_maxresdefault_1_5bef2a2c64",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 422,
                    "size": 39.27,
                    "path": null,
                    "url": "/uploads/medium_maxresdefault_1_5bef2a2c64.jpeg"
                },
                "small": {
                    "hash": "small_maxresdefault_1_5bef2a2c64",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 281,
                    "size": 21.26,
                    "path": null,
                    "url": "/uploads/small_maxresdefault_1_5bef2a2c64.jpeg"
                }
            },
            "hash": "maxresdefault_1_5bef2a2c64",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 76.32,
            "url": "/uploads/maxresdefault_1_5bef2a2c64.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:08:24.148Z",
            "updated_at": "2020-12-03T18:08:24.148Z"
        }
    },
    {
        "id": 85,
        "nameRU": "Слушая Москву",
        "nameEN": null,
        "director": "Иван Проскуряков",
        "country": "Россия",
        "year": "2015",
        "duration": 25,
        "description": "Москва стала домом и сценой для артистов из самых разных точек планеты. Музыка в этом городе звучит, не прекращаясь: венесуэлец-космополит, осевший в Москве, готовит презентацию альбома своей группы – важное событие андерграундной рок-сцены. Китаянка-пианистка из Консерватории, влюблённая в Рахманинова, готовится к серьёзному экзамену. Американка и казах экспериментируют с форматами и ищут слушателя среди соседей по подъезду, приглашая их на квартирник. Ансамбль кубинцев в очередной раз выходит на сцену ресторана с национальными песнями и плясками. Ганаянец-барабанщик играет вместе с госпел-хором на протестантской службе. Каждый из них существует в своих маленьких – доступных слушателю – мирах; и из этих миров и состоит музыкальный ландшафт Москвы.",
        "trailerLink": null,
        "created_at": "2020-12-03T18:12:14.334Z",
        "updated_at": "2020-12-03T18:12:14.334Z",
        "image": {
            "id": 86,
            "name": "750x485",
            "alternativeText": "",
            "caption": "",
            "width": 750,
            "height": 485,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_750x485_6aa18b04bb",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 241,
                    "height": 156,
                    "size": 6.55,
                    "path": null,
                    "url": "/uploads/thumbnail_750x485_6aa18b04bb.jpeg"
                },
                "small": {
                    "hash": "small_750x485_6aa18b04bb",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 323,
                    "size": 18.96,
                    "path": null,
                    "url": "/uploads/small_750x485_6aa18b04bb.jpeg"
                }
            },
            "hash": "750x485_6aa18b04bb",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 34.6,
            "url": "/uploads/750x485_6aa18b04bb.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:12:04.386Z",
            "updated_at": "2020-12-03T18:12:04.386Z"
        }
    },
    {
        "id": 86,
        "nameRU": "Ямаха",
        "nameEN": "Yamaha",
        "director": "Инна Омельченко",
        "country": "Россия",
        "year": "2015",
        "duration": 38,
        "description": "Герою фильма двадцать три года, и он обычный мечтатель. Работает продавцом в гипермаркете, живёт в коммуналке с рабочими мигрантами, попутно грезя о карьере музыканта. Никто не воспринимает его музыкальные устремления всерьёз: ни родственники, ни лучший друг, ни соседи. В особенности они… Но у героя есть старая «Ямаха», которая, по его мнению, должна привести к желанной мечте.",
        "trailerLink": "https://vimeo.com/138638860",
        "created_at": "2020-12-03T18:19:07.142Z",
        "updated_at": "2020-12-03T18:19:07.142Z",
        "image": {
            "id": 87,
            "name": "3_29",
            "alternativeText": "",
            "caption": "",
            "width": 1920,
            "height": 1080,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_3_29_4b376917c9",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 5.89,
                    "path": null,
                    "url": "/uploads/thumbnail_3_29_4b376917c9.jpeg"
                },
                "large": {
                    "hash": "large_3_29_4b376917c9",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 1000,
                    "height": 563,
                    "size": 49.07,
                    "path": null,
                    "url": "/uploads/large_3_29_4b376917c9.jpeg"
                },
                "medium": {
                    "hash": "medium_3_29_4b376917c9",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 422,
                    "size": 30.71,
                    "path": null,
                    "url": "/uploads/medium_3_29_4b376917c9.jpeg"
                },
                "small": {
                    "hash": "small_3_29_4b376917c9",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 281,
                    "size": 16.7,
                    "path": null,
                    "url": "/uploads/small_3_29_4b376917c9.jpeg"
                }
            },
            "hash": "3_29_4b376917c9",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 131.97,
            "url": "/uploads/3_29_4b376917c9.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:17:56.769Z",
            "updated_at": "2020-12-03T18:17:56.769Z"
        }
    },
    {
        "id": 87,
        "nameRU": "Костры и звезды",
        "nameEN": "Bonfires and Stars",
        "director": "Саша Воронов",
        "country": "Россия",
        "year": "2015",
        "duration": 50,
        "description": "Московский электронный музыкант Moa Pillar (Федор Переверзев) и основатель лэйбла Ored Recordings Булат Халилов встречаются в Нальчике и отправляются в путешествие по Кабардино-Балкарии и Адыгее. Каждый из них преследует свои цели, погружаясь в мир черкесской традиционной музыки. Федор ищет возможность сделать совместную запись с местными музыкантами, в то время как Булат все больше сомневается в уместности такого эксперимента.",
        "trailerLink": "https://www.youtube.com/watch?v=kDGB9l-5TKI",
        "created_at": "2020-12-03T18:21:09.276Z",
        "updated_at": "2020-12-03T18:21:09.276Z",
        "image": {
            "id": 88,
            "name": "upload-9120ff30-fa73-11e5-b942-b366214b09de",
            "alternativeText": "",
            "caption": "",
            "width": 885,
            "height": 498,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_upload_9120ff30_fa73_11e5_b942_b366214b09de_ff4e9a16b9",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 5,
                    "path": null,
                    "url": "/uploads/thumbnail_upload_9120ff30_fa73_11e5_b942_b366214b09de_ff4e9a16b9.jpeg"
                },
                "medium": {
                    "hash": "medium_upload_9120ff30_fa73_11e5_b942_b366214b09de_ff4e9a16b9",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 422,
                    "size": 31.39,
                    "path": null,
                    "url": "/uploads/medium_upload_9120ff30_fa73_11e5_b942_b366214b09de_ff4e9a16b9.jpeg"
                },
                "small": {
                    "hash": "small_upload_9120ff30_fa73_11e5_b942_b366214b09de_ff4e9a16b9",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 281,
                    "size": 15.88,
                    "path": null,
                    "url": "/uploads/small_upload_9120ff30_fa73_11e5_b942_b366214b09de_ff4e9a16b9.jpeg"
                }
            },
            "hash": "upload_9120ff30_fa73_11e5_b942_b366214b09de_ff4e9a16b9",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 42.01,
            "url": "/uploads/upload_9120ff30_fa73_11e5_b942_b366214b09de_ff4e9a16b9.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:19:48.711Z",
            "updated_at": "2020-12-03T18:19:48.711Z"
        }
    },
    {
        "id": 88,
        "nameRU": "Ладно хорошо",
        "nameEN": "Ok Good",
        "director": "Александра Кулак, Анна Корниенко, Юлия Курмангалина",
        "country": "Россия",
        "year": "2015",
        "duration": 20,
        "description": "Документальный мюзикл о жизни в российской глубинке где-то под Вологдой. Это звук: музыка, человеческий голос, и тишина.",
        "trailerLink": "https://www.youtube.com/watch?v=hLplLgpLvYs",
        "created_at": "2020-12-03T18:22:57.156Z",
        "updated_at": "2020-12-03T18:22:57.156Z",
        "image": {
            "id": 89,
            "name": "загруженное (2)",
            "alternativeText": "",
            "caption": "",
            "width": 344,
            "height": 146,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_2_946c91c6d8",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 104,
                    "size": 7.08,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_2_946c91c6d8.jpeg"
                }
            },
            "hash": "zagruzhennoe_2_946c91c6d8",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 11.15,
            "url": "/uploads/zagruzhennoe_2_946c91c6d8.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:22:44.416Z",
            "updated_at": "2020-12-03T18:22:44.416Z"
        }
    },
    {
        "id": 89,
        "nameRU": "Бледные строения",
        "nameEN": "Pale Buildings",
        "director": "Филипп Задорожный",
        "country": "Россия",
        "year": "2015",
        "duration": 8,
        "description": "Московский техно-дуэт Interchain предлагает воспринимать недостроенные здания как скульптуры, заостряя внимание на пересечении исторического и эстетического в замороженных стройках. Для погружения в тему, Евгений Горбунов и Андрей Ли исполняют импровизацию в одном из заброшенных строений, создавая собственную незавершенную аудиоконструкцию.",
        "trailerLink": "https://youtu.be/oMypBoQOP4Y",
        "created_at": "2020-12-03T18:25:56.658Z",
        "updated_at": "2020-12-03T18:25:56.658Z",
        "image": {
            "id": 90,
            "name": "maxresdefault (2)",
            "alternativeText": "",
            "caption": "",
            "width": 1280,
            "height": 720,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_maxresdefault_2_4747cae75c",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 5.7,
                    "path": null,
                    "url": "/uploads/thumbnail_maxresdefault_2_4747cae75c.jpeg"
                },
                "large": {
                    "hash": "large_maxresdefault_2_4747cae75c",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 1000,
                    "height": 563,
                    "size": 64.14,
                    "path": null,
                    "url": "/uploads/large_maxresdefault_2_4747cae75c.jpeg"
                },
                "medium": {
                    "hash": "medium_maxresdefault_2_4747cae75c",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 422,
                    "size": 40.65,
                    "path": null,
                    "url": "/uploads/medium_maxresdefault_2_4747cae75c.jpeg"
                },
                "small": {
                    "hash": "small_maxresdefault_2_4747cae75c",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 281,
                    "size": 19.92,
                    "path": null,
                    "url": "/uploads/small_maxresdefault_2_4747cae75c.jpeg"
                }
            },
            "hash": "maxresdefault_2_4747cae75c",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 75.72,
            "url": "/uploads/maxresdefault_2_4747cae75c.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:24:57.245Z",
            "updated_at": "2020-12-03T18:24:57.245Z"
        }
    },
    {
        "id": 90,
        "nameRU": "Златан. Начало",
        "nameEN": "Den Unge Zlatan",
        "director": "Фредрик Герттен, Магнус Герттен",
        "country": null,
        "year": "2015",
        "duration": 96,
        "description": "1999 год. На стене висит газета с неоспоримым заголовком «Бекхэм – лучший в мире». Перед камерой – мало кому известный 17-летний пацан, который заявляет: «Английский футбол – дерьмо».\n\nЭто нападающий шведского клуба «Мальме» Златан Ибрагимович, огромное самомнение которого равно его футбольному таланту, только талант этот еще надо раскрыть. Всего через пару лет игры в Швеции Ибрагимович в золотом пиджаке и розовой рубашке поедет за рекордную сумму в голландский «Аякс», где будут и драки, и дисквалификации, и конфликт с капитаном команды, но будут и голы – включая один, который обязательно надо увидеть, потому что пересказать его все равно не получится. Фильм Фредрика и Магнуса Герттенов показывает, откуда взялся самый харизматичный игрок современного футбола (если что, с этим определением согласятся и Месси, и Роналду) и подробнейшим образом освещает относительно малоизвестный период его карьеры.\n\nСамое ценное здесь – невероятные архивные съемки из Швеции: клубный оператор «Мальме», снимающий с расстояния вытянутой руки, ходит за Златаном и в раздевалку, и в автобус, и к нему домой, где он режется в приставку, а также показывает, как дети выпрашивают у него бутсы, а девушки – номер телефона. Ранний этап его карьеры не обходится без трудностей, но Ибрагимович расправляется с ними примерно так же эффектно, как оставляет в дураках сразу трех защитников в дерби с «Юргорденом» в 2001 году, – и так же убедительно, как в 2016-м завоевывает 29-й трофей в своей карьере.",
        "trailerLink": "https://youtu.be/Zbt9XjNhaMg",
        "created_at": "2020-12-03T18:27:41.881Z",
        "updated_at": "2020-12-03T18:27:41.881Z",
        "image": {
            "id": 91,
            "name": "den-unge-zlatan",
            "alternativeText": "",
            "caption": "",
            "width": 1440,
            "height": 750,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_den_unge_zlatan_aca9a6118e",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 128,
                    "size": 3.66,
                    "path": null,
                    "url": "/uploads/thumbnail_den_unge_zlatan_aca9a6118e.jpeg"
                },
                "large": {
                    "hash": "large_den_unge_zlatan_aca9a6118e",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 1000,
                    "height": 521,
                    "size": 31.99,
                    "path": null,
                    "url": "/uploads/large_den_unge_zlatan_aca9a6118e.jpeg"
                },
                "medium": {
                    "hash": "medium_den_unge_zlatan_aca9a6118e",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 391,
                    "size": 21.74,
                    "path": null,
                    "url": "/uploads/medium_den_unge_zlatan_aca9a6118e.jpeg"
                },
                "small": {
                    "hash": "small_den_unge_zlatan_aca9a6118e",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 260,
                    "size": 11.56,
                    "path": null,
                    "url": "/uploads/small_den_unge_zlatan_aca9a6118e.jpeg"
                }
            },
            "hash": "den_unge_zlatan_aca9a6118e",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 55.49,
            "url": "/uploads/den_unge_zlatan_aca9a6118e.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:27:21.915Z",
            "updated_at": "2020-12-03T18:27:21.915Z"
        }
    },
    {
        "id": 91,
        "nameRU": "Бег — это свобода",
        "nameEN": "Free to Run",
        "director": "Пьер Морат",
        "country": "Швейцария, Франция, Бельгия",
        "year": "2015",
        "duration": 90,
        "description": "Сегодня мало кто помнит, что еще 50 лет назад простым бегунам приходилось быть бунтарями — места в этом спорте официально не было ни женщинам, ни любителям.\n\nСитуацию изменили 60-е годы, время борьбы за права на всех фронтах. Начиная именно с 60-х, фильм рассказывает историю бега как культурного и даже контркультурного явления, от романтических провокаций до создания огромной индустрии.\n\nГлавные герои фильма — иконы бегового движения. Кэтрин Швитцер — первая женщина-марафонец: в 1967-м она отбивалась от директора Бостонского марафона, который силой пытался столкнуть ее с дистанции. Фотография этого момента обошла обложки мировых изданий, а ее героиня впоследствии стал лицом первого марафона для женщин и комментатором первого женского забега на Олимпийских играх 1984 года. Фред Лебоу — основатель Нью-Йоркского марафона, родившегося из крохотной ассоциации бегунов-волонтеров, которые тогда даже не могли представить, что когда-нибудь оккупируют Центральный парк. В 62 года он, уже зная, что болен раком мозга, пробежал марафон в качестве символического жеста, показывая себе и друзьям, что жив. Орегонец Стив Префонтейн — рекордсмен и борец за право всех талантливых «любителей» на профессиональную карьеру; в Голливуде о нем уже сняли два фильма. Это ода бегу как проявлению воли к жизни, способу единения с природой, а марафонам — как минутам славы для каждого.",
        "trailerLink": "https://www.youtube.com/watch?v=8SwarSKGj9",
        "created_at": "2020-12-03T18:35:20.550Z",
        "updated_at": "2020-12-03T18:35:20.550Z",
        "image": {
            "id": 92,
            "name": "загруженное (3)",
            "alternativeText": "",
            "caption": "",
            "width": 343,
            "height": 147,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_3_6dab3dce0f",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 105,
                    "size": 5.8,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_3_6dab3dce0f.jpeg"
                }
            },
            "hash": "zagruzhennoe_3_6dab3dce0f",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 9.31,
            "url": "/uploads/zagruzhennoe_3_6dab3dce0f.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:28:51.256Z",
            "updated_at": "2020-12-03T18:28:51.256Z"
        }
    },
    {
        "id": 92,
        "nameRU": "Горькое озеро",
        "nameEN": "Bitter Lake",
        "director": "Адам Кертис ",
        "country": "Великобритания",
        "year": "2015",
        "duration": 136,
        "description": "Последняя работа Адама Кертиса, пожалуй, самого известного телевизионщика в мире кино и самого неочевидного режиссера на современном британском телевидении. Эта диковатая комбинация исчерпывающе объясняет метод Кертиса: будучи штатным сотрудником BBC и имея неограниченный доступ к их архивам, он делает крайне визуальные фильмы-эссе, посвященные взаимосвязи власти, технического прогресса и их влиянию на политику и культуру, причем всегда с безупречным выбором музыки.\n\nЭто история об Афганистане и хрониках западного вмешательства на Ближнем Востоке, которое по мнению Кертиса, представляет собой череду непониманий и упрощений, раз за разом приводивших к результату, ровно противоположному планируемому. Америка защищала ваххабитов, чтобы иметь доступ к нефти Саудовской Аравии, в Афганистане строили дамбы, чтобы осушить Гильмендскую долину, таким образом готовя идеальную почву для выращивания опиумного мака. Прошлое усеяно предупреждениями, а история — это узор, только кто бы разглядел его, но сегодня история выглядит слишком сложной штукой для политиков, ее заменил сказочный миф про добро и зло, тем временем Исламское Государство желает примерно того же, чего хотели ваххабиты еще полвека назад. Фильм-провокация вызвал немало споров в Британии, но его кинематограческая ценность бесспорна — впечатляющий аудио-визуальный коллаж длиной в 137 минут, с цитатами из «Соляриса» Тарковского.",
        "trailerLink": "https://youtu.be/Kq4twiRwH6M",
        "created_at": "2020-12-03T18:36:50.935Z",
        "updated_at": "2020-12-03T18:36:50.935Z",
        "image": {
            "id": 93,
            "name": "загруженное (4)",
            "alternativeText": "",
            "caption": "",
            "width": 299,
            "height": 168,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_4_63633dbd00",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 4.59,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_4_63633dbd00.jpeg"
                }
            },
            "hash": "zagruzhennoe_4_63633dbd00",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 4.61,
            "url": "/uploads/zagruzhennoe_4_63633dbd00.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:36:37.808Z",
            "updated_at": "2020-12-03T18:36:37.808Z"
        }
    },
    {
        "id": 93,
        "nameRU": "Фонко",
        "nameEN": "Fonko",
        "director": "Ламин Даниель Ядама, Ларс Ловен, Йеран Ульссон",
        "country": null,
        "year": "2016",
        "duration": 87,
        "description": "Фильм о современной клубной сцене почти дюжины больших африканских столиц: Йоханнесбурга, Лагоса, Дакара — озвучен певицей Нене Черри и начинен фрагментами текстов и выступлений Фела Кути, одного из самых влиятельных африканских артистов и политических активистов. Его яркие и местами радикальные высказывания о борьбе с неоколониализмом, о том, что слово «демократия» не так уж далеко от «сумасшествия» (democrazy) соседствуют с не менее впечатляющими образами молодых африканских музыкантов, тех, кто готовит в домашних условиях африканскую танцевальную революцию.",
        "trailerLink": "https://youtu.be/0GdCj1KyJ1E",
        "created_at": "2020-12-03T18:38:32.276Z",
        "updated_at": "2020-12-03T18:38:32.276Z",
        "image": {
            "id": 94,
            "name": "81c+6fLedfL._RI_",
            "alternativeText": "",
            "caption": "",
            "width": 1600,
            "height": 1200,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_81c_6f_Ledf_L_RI_13c54761cc",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 208,
                    "height": 156,
                    "size": 8.91,
                    "path": null,
                    "url": "/uploads/thumbnail_81c_6f_Ledf_L_RI_13c54761cc.jpeg"
                },
                "large": {
                    "hash": "large_81c_6f_Ledf_L_RI_13c54761cc",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 1000,
                    "height": 750,
                    "size": 134.23,
                    "path": null,
                    "url": "/uploads/large_81c_6f_Ledf_L_RI_13c54761cc.jpeg"
                },
                "medium": {
                    "hash": "medium_81c_6f_Ledf_L_RI_13c54761cc",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 563,
                    "size": 77.91,
                    "path": null,
                    "url": "/uploads/medium_81c_6f_Ledf_L_RI_13c54761cc.jpeg"
                },
                "small": {
                    "hash": "small_81c_6f_Ledf_L_RI_13c54761cc",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 375,
                    "size": 38.66,
                    "path": null,
                    "url": "/uploads/small_81c_6f_Ledf_L_RI_13c54761cc.jpeg"
                }
            },
            "hash": "81c_6f_Ledf_L_RI_13c54761cc",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 332.32,
            "url": "/uploads/81c_6f_Ledf_L_RI_13c54761cc.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:38:19.277Z",
            "updated_at": "2020-12-03T18:38:19.277Z"
        }
    },
    {
        "id": 94,
        "nameRU": " Мы – X",
        "nameEN": "We Are X",
        "director": "Стивен Кайак",
        "country": "США, Великобритания",
        "year": "2016",
        "duration": 93,
        "description": "«Постоянно спрашивая: «Почему я здесь?» Что я делаю в этом мире?», я будто бы ищу причину для смерти. Вот почему я играю на барабанах так, будто никакого завтра не существует», — говорит в начале фильма Ёсики Хаяси, со-основатель одной из главных рок-групп Японии, X Japan.\n\nX Japan, в соответствии с названием, очень японская группа — в фильме рассказывается о чести, достоинстве, попытках выйти на западный рынок и том, что в любые моменты жизни ты должен быть готов к тому, чтобы выполнить волю императора. Все критики наперебой хвалят группу, ненадолго появляющиеся Стэн Ли, Джин Симмонс и Мэрилин Мэнсон склоняют голову в почтении, фанаты без ума от них, но на самом деле это фильм не об успехе и о том, как достичь в жизни всего, что хотел. «We Are X» лишь поначалу показывает только подготовку к важному для группы концерту в Madison Square Garden. Ёсики рассказывает о смерти отца и не стесняется показывать свои походы по врачам, лишь иногда отказываясь говорить о слишком личном. Тоси, вокалист и давний друг Ёсики, откровенно отвечает на вопросы о времени, проведённом в секте, и о временах, когда ему пришлось уйти из группы. Остальные участники скорее остаются на заднем плане — но лишь для того, чтобы подчеркнуть эту историю многолетней дружбы, пережившей смерть близких, срывы, непонимание и ссоры.",
        "trailerLink": "https://www.youtube.com/watch?v=l66IFX-H5Wo",
        "created_at": "2020-12-03T18:50:23.475Z",
        "updated_at": "2020-12-03T18:50:23.475Z",
        "image": {
            "id": 95,
            "name": "загруженное",
            "alternativeText": "",
            "caption": "",
            "width": 299,
            "height": 168,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_8e5b14a44a",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 10.7,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_8e5b14a44a.jpeg"
                }
            },
            "hash": "zagruzhennoe_8e5b14a44a",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 12.24,
            "url": "/uploads/zagruzhennoe_8e5b14a44a.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:50:08.354Z",
            "updated_at": "2020-12-03T18:50:08.354Z"
        }
    },
    {
        "id": 95,
        "nameRU": "В ожидании Б",
        "nameEN": "Waiting for B.",
        "director": "Пауло Сезар Толедо, Эбигейл Спиндел",
        "country": "Бразилия",
        "year": "2015",
        "duration": 71,
        "description": "«У меня все строго, если кто-то не пришел, я его просто из очереди выкидываю, я не шучу. Нечего прогуливать, пропал надолго — привози справку от врача!» — пылко сообщает юноша в очках, который организовал очередь на концерт Бейонсе в Сан-Паоло. Точнее, небольшой палаточный городок, потому что до концерта — еще два месяца.\n\nЗа эти два месяца городок превратится в настоящий карнавал — со своими дрэг-королевами, интригами, ежевечерними сеансами уличного тверка и умельцами по пошиву эпатажных костюмов.\n\n«В ожидании Б» — удивительный документ, исследующий одновременно феномен фанатства и жизнь отдельно взятого гей-коммьюнити через истории героев фильма, разговоры за жизнь в крохотном пространстве палаток и конечно же танцы. Герои рассказывают о себе и, каждый по-своему, объясняют, почему только в Бразилии возможны такие изматывающие, но полные восторга несколько недель на улице ради двух часов живой музыки. И, конечно, танцуют. Да так, что становится совершенно неясно, зачем Бейонсе везти в Сан-Паоло собственных танцоров — ведь там есть целая преданная армия, знающая каждое ее движение наизусть.\n\nА после фильма остается то щемящее ощущение, которое бывает только при отъезде из пионерлагеря.",
        "trailerLink": "https://www.youtube.com/watch?v=TnDTsA-aT8U",
        "created_at": "2020-12-03T18:54:49.534Z",
        "updated_at": "2020-12-03T18:54:49.534Z",
        "image": {
            "id": 96,
            "name": "загруженное (1)",
            "alternativeText": "",
            "caption": "",
            "width": 366,
            "height": 138,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_1_1aee5f7ecf",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 92,
                    "size": 7.31,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_1_1aee5f7ecf.jpeg"
                }
            },
            "hash": "zagruzhennoe_1_1aee5f7ecf",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 11.81,
            "url": "/uploads/zagruzhennoe_1_1aee5f7ecf.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:54:38.744Z",
            "updated_at": "2020-12-03T18:54:38.744Z"
        }
    },
    {
        "id": 96,
        "nameRU": "ЛеФ",
        "nameEN": null,
        "director": "Дмитрий Лавриненко",
        "country": "Украина",
        "year": "2016",
        "duration": 96,
        "description": "Бал у Воланда? Нет, Илья Хржановский снимает кино — и Леонид Федоров в его карнавальной стихии чувствует себя как рыба в воде. А вот и прибывающая под тревожные переборы «Зимы не будет» вода — всемирный потоп или просто Нева выходит из берегов, унося в туманную даль черный зонт? Танец огня — уличный цирк или геенна огненная? Режиссер Дмитрий Лавриненко, известный документальным фильмом о группе «АукцЫон» «Еще», монтирует историю Федорова из образов, равно сиюминутных и вечных, и историй, одновременно бытовых и надмирных. Фантомы и хроника, байки о записи первого сольного альбома в неотапливаемой студии Лендока, исповедальный рассказ о смерти отца, воспоминания о знакомстве с Анри Волохонским и Хвостом, напугавшим «батю» своей полной свободой от реальности, распитие водки на встрече с благодарными и не очень слушателями. За мозаичной картиной — цельный рассказ о тернистом пути художника, смелости выйти из зоны комфорта и духовной поэзии, которой фильм ищет визуальный эквивалент.",
        "trailerLink": "https://youtu.be/C2dTBYe-Y6I",
        "created_at": "2020-12-03T18:57:30.415Z",
        "updated_at": "2020-12-03T18:57:30.415Z",
        "image": {
            "id": 97,
            "name": "mqdefault",
            "alternativeText": "",
            "caption": "",
            "width": 320,
            "height": 180,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_mqdefault_14f34c8254",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 12.51,
                    "path": null,
                    "url": "/uploads/thumbnail_mqdefault_14f34c8254.jpeg"
                }
            },
            "hash": "mqdefault_14f34c8254",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 19.73,
            "url": "/uploads/mqdefault_14f34c8254.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:57:20.383Z",
            "updated_at": "2020-12-03T18:57:20.383Z"
        }
    },
    {
        "id": 97,
        "nameRU": "Олег и редкие искусства",
        "nameEN": "Oleg y las raras artes",
        "director": "Андрес Дуке",
        "country": "Испания",
        "year": "2016",
        "duration": 70,
        "description": "Олег Каравайчук – великий и загадочный композитор, живая достопримечательность Петербурга, почти мистическая личность без пола и возраста. На самом деле ему 89, но попробуйте в это поверить, глядя на этого вечного гуттаперчевого мальчика. Выходец из Венесуэлы Андрес Дюке совершил абсолютный режиссерский подвиг, уговорив вечно ускользающего Каравайчука на полноценные съемки. В геометрически выстроенных проходах по Эрмитажу Олег Николаевич – усталый путник, извлекающий энергию из искусства древних миров, того естественного «новаторства, которое не доминирует», и ценитель имперской красоты, объсняющийся в любви Екатерине, «влагалищу мироздания». В прогулках по Комарово – ворчливый и аррогантный старик, добрым словом поминающий Сталина («он выиграл войну и творчество») и мечтающий дожить до Страшного суда, когда неприятные соседи исчезнут с лица земли, а срубленные ими ели возродятся из мертвых. Но главные эпизоды – те, где Каравайчук играет свои «неудобные, но гениальные» мелодии, и руки музыканта, вступая в контакт с клавишами, будто отделяются от тела и превращаются в новый, инопланетный организм.",
        "trailerLink": "https://youtu.be/wV9wjT8Ayzw",
        "created_at": "2020-12-03T18:59:24.783Z",
        "updated_at": "2020-12-03T18:59:24.783Z",
        "image": {
            "id": 98,
            "name": "загруженное (2)",
            "alternativeText": "",
            "caption": "",
            "width": 313,
            "height": 161,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_2_d22375c7cf",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 126,
                    "size": 3.94,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_2_d22375c7cf.jpeg"
                }
            },
            "hash": "zagruzhennoe_2_d22375c7cf",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 4.01,
            "url": "/uploads/zagruzhennoe_2_d22375c7cf.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T18:57:54.033Z",
            "updated_at": "2020-12-03T18:57:54.033Z"
        }
    },
    {
        "id": 98,
        "nameRU": "Джунун",
        "nameEN": "Junun",
        "director": "Пол Томас Андерсон",
        "country": "США",
        "year": "2015",
        "duration": 54,
        "description": "С десяток музыкантов сидят на полу в кругу, во главе — израильский композитор Шай Бен-Цур, чуть поодаль — Джонни Гринвуд, спрятавший лицо за длинной челкой, за кадром — Найджел Годрич, за камерой — режиссер Пол Томас Андерсон. А за окном — весна в индийском Раджастане. Люди играют музыку небесной красоты и переглядываются друг с другом — когда серьезно, когда посмеиваясь.\n\nДокументальный фильм о поездке Гринвуда, Годрича и Шай Бен-Цура в Раджастан почти целиком состоит из бесконечных репетиций в просторном зале старинного индийского форта, продуваемом всеми ветрами из открытых окон и дверей. Разбавляют их лишь кроткие интервью местных музыкантов из Rajastan Express, редкие вылазки на рынок за починкой инструментов и — в качестве внезапной шалости — пристальное внимание камеры к залетающим то и дело в помещение голубям. Но большего и не надо: достаточно просидеть в зале десять минут, чтобы понять, что все эти люди собрались в кадре ради музыки, и пока она звучит, говорить им много совершенно ни к чему.\n\n",
        "trailerLink": "https://youtu.be/huHRo01P938",
        "created_at": "2020-12-03T19:02:02.158Z",
        "updated_at": "2020-12-03T19:02:02.158Z",
        "image": {
            "id": 99,
            "name": "загруженное (3)",
            "alternativeText": "",
            "caption": "",
            "width": 300,
            "height": 168,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_3_c78d64a9f0",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 137,
                    "size": 9.93,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_3_c78d64a9f0.jpeg"
                }
            },
            "hash": "zagruzhennoe_3_c78d64a9f0",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 10.46,
            "url": "/uploads/zagruzhennoe_3_c78d64a9f0.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T19:01:21.862Z",
            "updated_at": "2020-12-03T19:01:21.862Z"
        }
    },
    {
        "id": 99,
        "nameRU": "Дженис: Маленькая девочка грустит",
        "nameEN": "Janis: Little Girl Blue",
        "director": "Эми Берг",
        "country": "США",
        "year": "2015",
        "duration": 103,
        "description": "В родном Порт-Артуре она всегда чувствовала себя изгоем. Найдя близких по духу людей в Сан-Франциско, Дженис Джоплин стала суперзвездой — но совсем ненадолго. «Грустная маленькая девочка», один из немногих фильмов о быстрой, яркой и бурной жизни одной из главных рок-певиц в истории, сделан однажды номинировавшейся на «Оскар» Эми Берг без излишней сентиментальности, зато с большими почтением и любовью. О Джоплин нежно и без осуждения рассказывают ее друзья, родственники и игравшие с ней музыканты. Они вспоминают, как Дженис при первой встрече с Бобом Диланом заявила ему, что тоже станет знаменитой; как она не могла понять, почему не получается стать такой же, как все — и слава богу; как любила вообще весь мир — и почему это было проблемой. В перерывах между интервью — песни, записи концертов, бешеная энергетика которых прорывается через экран, и голос Кэт Пауэр, читающий письма, которые Дженис успела написать за свои 27.",
        "trailerLink": "https://youtu.be/Hefit0jYmfw",
        "created_at": "2020-12-03T19:04:57.589Z",
        "updated_at": "2020-12-03T19:04:57.589Z",
        "image": {
            "id": 100,
            "name": "загруженное (4)",
            "alternativeText": "",
            "caption": "",
            "width": 309,
            "height": 163,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_zagruzhennoe_4_43cd3f60e9",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 129,
                    "size": 5.79,
                    "path": null,
                    "url": "/uploads/thumbnail_zagruzhennoe_4_43cd3f60e9.jpeg"
                }
            },
            "hash": "zagruzhennoe_4_43cd3f60e9",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 7.08,
            "url": "/uploads/zagruzhennoe_4_43cd3f60e9.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T19:02:47.581Z",
            "updated_at": "2020-12-03T19:02:47.581Z"
        }
    },
    {
        "id": 100,
        "nameRU": "Зигги Звёздная Пыль и пауки с Марса",
        "nameEN": " Ziggy Stardust and the Spiders from Mars",
        "director": " Д.А. Пеннебейкер",
        "country": "Великобритания",
        "year": "1973",
        "duration": 90,
        "description": "3 июля 1973 года Дэвид Боуи вышел на сцену лондонского Hammersmith Odeon, чтобы дать свой последний концерт в образе Зигги Стардаста. О том, что это прощальное выступление космического мессии, не знал заранее никто, включая музыкантов группы и режиссера Д.А. Пеннбейкера, который вообще-то пришел туда снять двадцатиминутный промофильм, но, увидев Боуи на сцене, остался и запечатлел все, включая бесчисленные наряды артиста и полуживые от счастья толпы фанатов в партере.\n\n«Зигги Стардаст» — это памятник на экране, созданный при жизни, почти случайная и вполне удачная попытка ухватить лицо героя, постоянно меняющего обличье. Ставший сегодня классикой документального кино концертный фильм Пеннебейкер в итоге разбавил лишь несколькими дублями артиста за сценой. Их, впрочем, достаточно для того, чтобы обозначить тот самый зазор, который создавал в Боуи бешеный магнетизм — зазор между персонажем и человеком, от которого трудно отвести взгляд.",
        "trailerLink": "https://www.youtube.com/watch?v=Y1p11rvnR1o",
        "created_at": "2020-12-03T19:06:45.345Z",
        "updated_at": "2020-12-03T19:06:45.345Z",
        "image": {
            "id": 101,
            "name": "big_davidandthespidersper011",
            "alternativeText": "",
            "caption": "",
            "width": 736,
            "height": 480,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_big_davidandthespidersper011_2cef9d8735",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 239,
                    "height": 156,
                    "size": 10.93,
                    "path": null,
                    "url": "/uploads/thumbnail_big_davidandthespidersper011_2cef9d8735.jpeg"
                },
                "small": {
                    "hash": "small_big_davidandthespidersper011_2cef9d8735",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 326,
                    "size": 38.03,
                    "path": null,
                    "url": "/uploads/small_big_davidandthespidersper011_2cef9d8735.jpeg"
                }
            },
            "hash": "big_davidandthespidersper011_2cef9d8735",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 62.88,
            "url": "/uploads/big_davidandthespidersper011_2cef9d8735.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-03T19:06:27.399Z",
            "updated_at": "2020-12-03T19:06:27.399Z"
        }
    },
    {
        "id": 101,
        "nameRU": "SOS матросу!",
        "nameEN": "Vladivostok Vacation and the Great Russian Break",
        "director": "Дэнни Дрисдейл",
        "country": "США, Россия",
        "year": "2016",
        "duration": 50,
        "description": "Возможно, первый в мире фильм в жанре документальной музыкальной фантасмагории, «SOS Матросу!» – это рок-н-ролльное безумие в традициях «Help!», но под парусом, на всех широтах, в мире, в котором Желтая подводная лодка, наконец, встретилась с капитаном Врунгелем.\n\nВсе начинается в порту Владивостока. Музыкант Илья, решивший, что его группе тесен родной город, мечтает о международном признании, особенно – о премии «Грэмми». Его жизнь меняет случайная встреча с капитаном парусного судна, который предлагает музыканту место на борту. Вскоре Илья и его товарищи по группе – Олег, Юрий и Евгений – оказываются в настоящем кругосветном путешествии. Маршрут прост: «побывать в тех местах, где любят рок-н-ролл!»\n\nНо не все так просто, как кажется на первый взгляд. Поэтичный гитарист Юрий не жалует море, мечтает быстрее покинуть корабль и коротает время за стаканом. Барабанщик Олег, наоборот, начинает с удовольствием выполнять все матросские обязанности. Мечтательный бас-гитарист Евгений ищет золотую рыбку, которая исполнила бы все его желания. Тем временем мистер Spoon, друг детства героев, спонтанно решивший стать их менеджером, тоже поднимается на борт – что сыграет роковую роль в судьбе коллектива.\nТем временем за бортом сменяют друг друга Китай, Корея, Япония, Южная Африка, Лос-Анджелес. Запись новых песен прямо в каюте, концерты на улицах морских портов и неожиданные встречи. Добьются ли музыканты своего, поймают ли золотую рыбку и вынесут ли испытание морем?",
        "trailerLink": "https://www.youtube.com/watch?v=i8pUsJDjTR0",
        "created_at": "2020-12-15T17:05:49.825Z",
        "updated_at": "2020-12-15T17:05:49.825Z",
        "image": {
            "id": 102,
            "name": "maxresdefault",
            "alternativeText": "",
            "caption": "",
            "width": 1280,
            "height": 720,
            "formats": {
                "thumbnail": {
                    "hash": "thumbnail_maxresdefault_c1369083db",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 245,
                    "height": 138,
                    "size": 7.73,
                    "path": null,
                    "url": "/uploads/thumbnail_maxresdefault_c1369083db.jpeg"
                },
                "large": {
                    "hash": "large_maxresdefault_c1369083db",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 1000,
                    "height": 563,
                    "size": 66.2,
                    "path": null,
                    "url": "/uploads/large_maxresdefault_c1369083db.jpeg"
                },
                "medium": {
                    "hash": "medium_maxresdefault_c1369083db",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 750,
                    "height": 422,
                    "size": 44.27,
                    "path": null,
                    "url": "/uploads/medium_maxresdefault_c1369083db.jpeg"
                },
                "small": {
                    "hash": "small_maxresdefault_c1369083db",
                    "ext": ".jpeg",
                    "mime": "image/jpeg",
                    "width": 500,
                    "height": 281,
                    "size": 23.66,
                    "path": null,
                    "url": "/uploads/small_maxresdefault_c1369083db.jpeg"
                }
            },
            "hash": "maxresdefault_c1369083db",
            "ext": ".jpeg",
            "mime": "image/jpeg",
            "size": 80.97,
            "url": "/uploads/maxresdefault_c1369083db.jpeg",
            "previewUrl": null,
            "provider": "local",
            "provider_metadata": null,
            "created_at": "2020-12-15T17:05:25.590Z",
            "updated_at": "2020-12-15T17:05:25.590Z"
        }
    }
]

export const savedMovies = [
    {
        "movieId": 2,
        "nameRU": "All Tomorrow's Parties",
        "nameEN": "All Tomorrow's Parties",
        "description": "Хроники британского фестиваля, который первым нарушил монополию «Гластонбери».",
        "duration": 82,
        "year": "2009",
        "country": "Великобритания",
        "director": " Джонатан Кауэтт",
        "image": "https://api.nomoreparties.co/uploads/all_tommoros_parties_33a125248d.jpeg",
        "trailer": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
        "thumbnail": "https://api.nomoreparties.co/uploads/thumbnail_all_tommoros_parties_33a125248d.jpeg",
        "owner": "1"
    },
    {
        "movieId": 5,
        "nameRU": "Taqwacore: The Birth of Punk Islam",
        "nameEN": "Taqwacore: The Birth of Punk Islam",
        "description": "**Don't panic, we're Islamic!**",
        "duration": 80,
        "year": "2009",
        "country": "Канада",
        "director": " Омар Маджид",
        "image": "https://api.nomoreparties.co/uploads/taqwacore2_2f487d2e74.jpeg",
        "trailer": "https://www.youtube.com/watch?v=D5fBhbEJxEU",
        "thumbnail": "https://api.nomoreparties.co/uploads/thumbnail_taqwacore2_2f487d2e74.jpeg",
        "owner": "1"
    }

]

export const user = {
    "_id": "61c9f17d9514baf95bfc1067",
    "name": "Test User",
    "email": "testuser@mail.ru",
}